import { ScrollView, Button, CheckBox, SpinBox, Slider, GroupBox, LineEdit, StandardListView,
    ComboBox, HorizontalBox, VerticalBox, GridBox, TabWidget, TextEdit, Slider } from "std-widgets.slint";

App := Window {
    preferred-width: 1000px;
    preferred-height: 1000px;
    title: "galtland";

    callback stream_id_input(string);

    property window_width <=> width;
    property window_height <=> height;
    property<bool> is_paused;
    property<float> seek_position: 0;
    property<string> ts_label: "00:00:00 / 00:00:00";

    property<image> play_icon: @image-url("../assets/play-solid.svg");
    property<image> pause_icon: @image-url("../assets/pause-solid.svg");

    property<float> new_position: 0;
    property<bool> position_ackd: true;

    VerticalBox {
        Rectangle {
            background: #ffffffaa;
            height: 50px;
            GroupBox {
                title: "Stream view";
                text_stream_id := LineEdit {
                    placeholder-text: "Enter a stream id (e.g live/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN)";
                    accepted(text) => { stream_id_input(text); }
                }
                Button {
                    text: "Go";
                    clicked => {
                        stream_id_input(text_stream_id.text);
                    }
                }
            }
        }

        Rectangle {
            background: #ffffff00;
        }

        Rectangle {
            background: #ffffffaa;
            height: 50px;
            HorizontalBox {
                HorizontalLayout {
                    Button {
                        width: 55px;
                        icon: !is_paused ? pause_icon : play_icon;
                        clicked => {
                            is_paused = !is_paused;
                        }
                    }
                    HorizontalBox {
                        horizontal-stretch: 1;
                        padding-top: 12px;

                        Slider {
                            width: 100%;
                            height: 12px;
                            value: seek_position * 100;
                            changed(value) => {
                                new_position = value;
                                position_ackd = false;
                                seek_position = value;
                            }
                        }
                    }
                    HorizontalBox {
                        padding-top: 12px;
                        Text {
                            text: ts_label;
                            color: #000000;
                        }
                    }
                }
            }
        }
    }
}
